# Generated by Django 3.2.4 on 2021-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smtmember',
            options={'verbose_name': 'Committee Member'},
        ),
        migrations.AddField(
            model_name='smtmember',
            name='eicc_member',
            field=models.BooleanField(default=False, verbose_name='EICC Member'),
        ),
        migrations.AddField(
            model_name='smtmember',
            name='smc_member',
            field=models.BooleanField(default=False, verbose_name='SMC Member'),
        ),
    ]
