# Generated by Django 3.2.4 on 2021-06-10 04:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nepali_datetime_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, help_text="Write tags separated with commas like 'tag1, tag2, tag3'", null=True)),
                ('document_type', models.CharField(blank=True, choices=[('Application', 'Application'), ('Letter', 'Letter'), ('Minute', 'Minute'), ('Proposal', 'Proposal'), ('Report', 'Report'), ('Research Paper', 'Research Paper'), ('Resume', 'Resume'), ('Thesis', 'Thesis'), ('Minute', 'Minute'), ('Others', 'Others')], max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/document/')),
                ('calendar', models.CharField(choices=[('BS', 'BS'), ('AD', 'AD')], max_length=255)),
                ('date_of_submission_BS', nepali_datetime_field.models.NepaliDateField(blank=True, help_text='Write in YYYY-MM-DD format', null=True)),
                ('created_on_BS', nepali_datetime_field.models.NepaliDateField(blank=True, help_text='Write in YYYY-MM-DD format', null=True)),
                ('last_updated_on_BS', nepali_datetime_field.models.NepaliDateField(blank=True, help_text='Write in YYYY-MM-DD format', null=True)),
                ('date_of_submission_AD', models.DateField(blank=True, null=True)),
                ('created_on_AD', models.DateField(blank=True, null=True)),
                ('last_updated_on_AD', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dss')),
            ],
        ),
    ]
