# Generated by Django 3.2.4 on 2021-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/trainer/experience'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/trainer/qualification'),
        ),
    ]
