# Generated by Django 3.2.4 on 2021-08-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='targeted_budget',
            new_name='estimated_cost',
        ),
    ]
