from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from nepali_datetime_field.models import NepaliDateField

from course.models import Course
from dss.models import DSS
from location.models import Province, District, Municipality


# Create your models here.
class Trainer(models.Model):
    # Regex Validators
    phone_regex = RegexValidator(regex=r'^(9\d{9}|0\d{1,2}-\d{6})$')

    # Choices
    GENDERS = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Sexual Minority', 'Sexual Minority')
    )
    MARITAL_STATUS = (
        ('Unmarried', 'Unmarried'),
        ('Married', 'Married'),
        ('Multimarried', 'Multimarried'),
        ('Widow', 'Widow'),
        ('Divorced', 'Divorced'),
        ('Separated', 'Separated')
    )
    MIGRATION_STATUS = (
        ('Internal Migrant', 'Internal Migrant'),
        ('Returnee', 'Returnee'),
        ('None', 'None')
    )
    SPECIAL_FOCUS_GROUP = (
        ('Halaiya', 'Halaiya'),
        ('Kamaiya', 'Kamaiya'),
        ('HIV Infected', 'HIV Infected'),
        ('Single Women', 'Single Women'),
        ('None', 'None')
    )
    ETHNICITIES = (
        ('Khas/Chhetri', 'Khas/Chhetri'),
        ('Brahmin-Hill/Bahun', 'Brahmin-Hill/Bahun'),
        ('Magar', 'Magar'),
        ('Tharu', 'Tharu'),
        ('Tamang', 'Tamang'),
        ('Newar', 'Newar'),
        ('Kami', 'Kami'),
        ('Musalman/Nepali Muslims', 'Musalman/Nepali Muslims'),
        ('Yadav Yadav/Ahir', 'Yadav Yadav/Ahir'),
        ('Rai', 'Rai'),
        ('Gurung', 'Gurung'),
        ('Damai/Dholi', 'Damai/Dholi'),
        ('Thakuri	Khas', 'Thakuri	Khas'),
        ('Limbu', 'Limbu'),
        ('Sarki', 'Sarki'),
        ('Teli', 'Teli'),
        ('Chamar/Harijan/Ram', 'Chamar/Harijan/Ram'),
        ('Kushwaha', 'Kushwaha'),
        ('Musahar', 'Musahar'),
        ('Kurmi', 'Kurmi'),
        ('Sanyasi/Dasnami', 'Sanyasi/Dasnami'),
        ('Dhanuk', 'Dhanuk'),
        ('Kanu/Haluwai', 'Kanu/Haluwai'),
        ('Dusadh/Pasawan/Pasi', 'Dusadh/Pasawan/Pasi'),
        ('Mallaha', 'Mallaha'),
        ('Kewat', 'Kewat'),
        ('Kathabaniyan', 'Kathabaniyan'),
        ('Brahmin-Tarai', 'Brahmin-Tarai'),
        ('Kalwar', 'Kalwar'),
        ('Kanu', 'Kanu'),
        ('Kumal', 'Kumal'),
        ('Bhujel', 'Bhujel'),
        ('Hajam/Thakur', 'Hajam/Thakur'),
        ('Rajbanshi', 'Rajbanshi'),
        ('Sherpa', 'Sherpa'),
        ('Dhobi', 'Dhobi'),
        ('Tatma/Tatwa', 'Tatma/Tatwa'),
        ('Lohar', 'Lohar'),
        ('Khatwe', 'Khatwe'),
        ('Sudhi', 'Sudhi'),
        ('Danuwar', 'Danuwar'),
        ('Majhi', 'Majhi'),
        ('Barai', 'Barai'),
        ('Bin', 'Bin'),
        ('Nuniya', 'Nuniya'),
        ('Chepang', 'Chepang'),
        ('Sonar', 'Sonar'),
        ('Kumhar', 'Kumhar'),
        ('Sunwar', 'Sunwar'),
        ('Bantar/Sardar', 'Bantar/Sardar'),
        ('Kahar', 'Kahar'),
        ('Santhal', 'Santhal'),
        ('Marwadi', 'Marwadi'),
        ('Kayastha', 'Kayastha'),
        ('Rajput/Terai', 'Rajput/Terai'),
        ('Badi', 'Badi'),
        ('Jhangar/Uraon', 'Jhangar/Uraon'),
        ('Gangai', 'Gangai'),
        ('Lodh', 'Lodh'),
        ('Badhaee', 'Badhaee'),
        ('Thami', 'Thami'),
        ('Kulung', 'Kulung'),
        ('Bengali', 'Bengali'),
        ('Gaderi/Bhediyar/Gangajali', 'Gaderi/Bhediyar/Gangajali'),
        ('Dhimal', 'Dhimal'),
        ('Yakkha', 'Yakkha'),
        ('Ghale', 'Ghale'),
        ('Tajpuriya', 'Tajpuriya'),
        ('Khawas', 'Khawas'),
        ('Darai', 'Darai'),
        ('Mali', 'Mali'),
        ('Dhuniya', 'Dhuniya'),
        ('Pahari', 'Pahari'),
        ('Rajdhob', 'Rajdhob'),
        ('Bhote', 'Bhote'),
        ('Dom', 'Dom'),
        ('Thakali', 'Thakali'),
        ('Kori', 'Kori'),
        ('Chhantyal', 'Chhantyal'),
        ('Hyolmo', 'Hyolmo'),
        ('Bote', 'Bote'),
        ('Rajbhar', 'Rajbhar'),
        ('Brahmu/Baramo', 'Brahmu/Baramo'),
        ('Punjabi', 'Punjabi'),
        ('Nachhring', 'Nachhring'),
        ('Yamphu', 'Yamphu'),
        ('Gaine', 'Gaine'),
        ('Chamling', 'Chamling'),
        ('Athpahariya', 'Athpahariya'),
        ('Jirel', 'Jirel'),
        ('Dura', 'Dura'),
        ('Sarabaria', 'Sarabaria'),
        ('Meche', 'Meche'),
        ('Bantaba', 'Bantaba'),
        ('Raji', 'Raji'),
        ('Dolpo', 'Dolpo'),
        ('Halkhor', 'Halkhor'),
        ('Byansi/Sauka', 'Byansi/Sauka'),
        ('Amat', 'Amat'),
        ('Thulung', 'Thulung'),
        ('Lepcha', 'Lepcha'),
        ('Pathakatta/Kushwadia', 'Pathakatta/Kushwadia'),
        ('Mewahang', 'Mewahang'),
        ('Bahing', 'Bahing'),
        ('Natuwa', 'Natuwa'),
        ('Hayu', 'Hayu'),
        ('Dhankar/Dharikar', 'Dhankar/Dharikar'),
        ('Lhopa', 'Lhopa'),
        ('Munda', 'Munda'),
        ('Dev', 'Dev'),
        ('Dhandi', 'Dhandi'),
        ('Kamar', 'Kamar'),
        ('Kisan', 'Kisan'),
        ('Sampang', 'Sampang'),
        ('Koche', 'Koche'),
        ('Lhomi', 'Lhomi'),
        ('Khaling', 'Khaling'),
        ('Topkegola', 'Topkegola'),
        ('Chidimar', 'Chidimar'),
        ('Walung', 'Walung'),
        ('Lohorung', 'Lohorung'),
        ('Kalar', 'Kalar'),
        ('Raute', 'Raute'),
        ('Nurang', 'Nurang'),
        ('Kusunda', 'Kusunda'),
        ('Foreigners', 'Foreigners'),
        ('Others/Undefined', 'Others/Undefined')
    )
    RELIGIONS = (
        ('No Religion', 'No Religion'),
        ('Buddhism', 'Buddhism'),
        ('Christianity', 'Christianity'),
        ('Hinduism', 'Hinduism'),
        ('Jainism', 'Jainism'),
        ('Kiratism', 'Kiratism'),
        ('Sikhism', 'Sikhism'),
        ('Others', 'Others'),
    )
    WARD_NUMBER = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (12, 12),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (18, 18),
        (19, 19),
        (20, 20),
        (21, 21),
        (22, 22),
        (23, 23),
        (24, 24),
        (25, 25),
        (26, 26),
        (27, 27),
        (28, 28),
        (29, 29),
        (30, 30),
        (31, 31),
        (32, 32),
    )
    MUNICIPALITIES = (
        ('Phaktanlung', 'Phaktanlung'),
        ('Mikwakhola', 'Mikwakhola'),
        ('Meringden', 'Meringden'),
        ('Maiwakhola', 'Maiwakhola'),
        ('Aatharai Tribeni', 'Aatharai Tribeni'),
        ('Phungling', 'Phungling'),
        ('Yangwarak', 'Yangwarak'),
        ('Sirijanga', 'Sirijanga'),
        ('Sidingba', 'Sidingba'),
        ('Bhotkhola', 'Bhotkhola'),
        ('Makalu', 'Makalu'),
        ('Silichong', 'Silichong'),
        ('Chichila', 'Chichila'),
        ('Sabhapokhari', 'Sabhapokhari'),
        ('Khandabari', 'Khandabari'),
        ('Panchakhapan', 'Panchakhapan'),
        ('Chainapur', 'Chainapur'),
        ('Madi', 'Madi'),
        ('Dharmadevi', 'Dharmadevi'),
        ('Khumbu Pasanglhamu', 'Khumbu Pasanglhamu'),
        ('Mahakulung', 'Mahakulung'),
        ('Sotang', 'Sotang'),
        ('Dhudhakoshi', 'Dhudhakoshi'),
        ('Dhudha Koushika', 'Dhudha Koushika'),
        ('Necha Salyan', 'Necha Salyan'),
        ('Solu Dhudhakunda', 'Solu Dhudhakunda'),
        ('Likhu Pike', 'Likhu Pike'),
        ('Chishankhu Gadhi', 'Chishankhu Gadhi'),
        ('Siddhicharan', 'Siddhicharan'),
        ('Molung', 'Molung'),
        ('Khiji Demba', 'Khiji Demba'),
        ('Likhu', 'Likhu'),
        ('Champadevi', 'Champadevi'),
        ('Sunkoshi', 'Sunkoshi'),
        ('Manebhanjyang', 'Manebhanjyang'),
        ('Kepilasgadhi', 'Kepilasgadhi'),
        ('Aiselukharka', 'Aiselukharka'),
        ('Lamidanda', 'Lamidanda'),
        ('Halesi Tuwachung', 'Halesi Tuwachung'),
        ('Rupakot Majhuwagadhi', 'Rupakot Majhuwagadhi'),
        ('Sakela', 'Sakela'),
        ('Diprung', 'Diprung'),
        ('Khotehang', 'Khotehang'),
        ('Jante Dhunga', 'Jante Dhunga'),
        ('Baraha Pokhari', 'Baraha Pokhari'),
        ('Shadananda', 'Shadananda'),
        ('Salpa Silichho', 'Salpa Silichho'),
        ('Tyamke Maiyum', 'Tyamke Maiyum'),
        ('Bhojpur', 'Bhojpur'),
        ('Arun', 'Arun'),
        ('Pauwa Dunma', 'Pauwa Dunma'),
        ('Ramprasad Rai', 'Ramprasad Rai'),
        ('Hatuwagadhi', 'Hatuwagadhi'),
        ('Aamchowk', 'Aamchowk'),
        ('Mahalaxmi', 'Mahalaxmi'),
        ('Pakhribas', 'Pakhribas'),
        ('Chhathar Jorpati', 'Chhathar Jorpati'),
        ('Dhankuta', 'Dhankuta'),
        ('Khalsa Chhintang Sahidbhumi', 'Khalsa Chhintang Sahidbhumi'),
        ('Sangurigadhi', 'Sangurigadhi'),
        ('Chaubise', 'Chaubise'),
        ('Aatharai', 'Aatharai'),
        ('Phedap', 'Phedap'),
        ('Menchhayayem', 'Menchhayayem'),
        ('Myanglung', 'Myanglung'),
        ('Laligurans', 'Laligurans'),
        ('Chhathar', 'Chhathar'),
        ('Yangbarak', 'Yangbarak'),
        ('Hilihan', 'Hilihan'),
        ('Falelung', 'Falelung'),
        ('Phidim', 'Phidim'),
        ('Falgunanda', 'Falgunanda'),
        ('Kummayak', 'Kummayak'),
        ('Tumbewa', 'Tumbewa'),
        ('Miklajung', 'Miklajung'),
        ('Mai Jogmai', 'Mai Jogmai'),
        ('Sandakpur', 'Sandakpur'),
        ('Ilam', 'Ilam'),
        ('Deumai', 'Deumai'),
        ('Fakfokathum', 'Fakfokathum'),
        ('Mangsebung', 'Mangsebung'),
        ('Chulachuli', 'Chulachuli'),
        ('Mai', 'Mai'),
        ('Suryodaya', 'Suryodaya'),
        ('Rong', 'Rong'),
        ('Mechinagar', 'Mechinagar'),
        ('Buddhashanti', 'Buddhashanti'),
        ('Arjundhara', 'Arjundhara'),
        ('Kankai', 'Kankai'),
        ('Shivasatakshi', 'Shivasatakshi'),
        ('Kamal', 'Kamal'),
        ('Damak', 'Damak'),
        ('Gauradaha', 'Gauradaha'),
        ('Gauriganj', 'Gauriganj'),
        ('Jhapa', 'Jhapa'),
        ('Barhadashi', 'Barhadashi'),
        ('Birtamod', 'Birtamod'),
        ('Haldibari', 'Haldibari'),
        ('Bhadrapur', 'Bhadrapur'),
        ('Kachanakawal', 'Kachanakawal'),
        ('Miklajung', 'Miklajung'),
        ('Letang', 'Letang'),
        ('Kerabari', 'Kerabari'),
        ('Sundarharaicha', 'Sundarharaicha'),
        ('Belbari', 'Belbari'),
        ('Kanepokhari', 'Kanepokhari'),
        ('Pathari Shanishchare', 'Pathari Shanishchare'),
        ('Urlabari', 'Urlabari'),
        ('Ratuwamai', 'Ratuwamai'),
        ('Sunwarshi', 'Sunwarshi'),
        ('Rangeli', 'Rangeli'),
        ('Gramthan', 'Gramthan'),
        ('Budhiganga', 'Budhiganga'),
        ('Biratnagar', 'Biratnagar'),
        ('Katahari', 'Katahari'),
        ('Dhanapalthan', 'Dhanapalthan'),
        ('Jahada', 'Jahada'),
        ('Dharan', 'Dharan'),
        ('Baraha', 'Baraha'),
        ('Koshi', 'Koshi'),
        ('Bhokraha', 'Bhokraha'),
        ('Ramdhuni', 'Ramdhuni'),
        ('Itahari', 'Itahari'),
        ('Duhabi', 'Duhabi'),
        ('Gadhi', 'Gadhi'),
        ('Inaruwa', 'Inaruwa'),
        ('Harinagara', 'Harinagara'),
        ('Dewangunj', 'Dewangunj'),
        ('Barju', 'Barju'),
        ('Belaka', 'Belaka'),
        ('Chaudandigadhi', 'Chaudandigadhi'),
        ('Triyuga', 'Triyuga'),
        ('Rautamai', 'Rautamai'),
        ('Sunkoshi', 'Sunkoshi'),
        ('Tapli', 'Tapli'),
        ('Katari', 'Katari'),
        ('Udayapurgadhi', 'Udayapurgadhi'),
        ('Saptakoshi', 'Saptakoshi'),
        ('Kanchanrup', 'Kanchanrup'),
        ('Agnisair Krishna Sabaran', 'Agnisair Krishna Sabaran'),
        ('Rupani', 'Rupani'),
        ('Shambhunath', 'Shambhunath'),
        ('Khadak', 'Khadak'),
        ('Surunga', 'Surunga'),
        ('Balan-Bihul', 'Balan-Bihul'),
        ('BodeBarsain', 'BodeBarsain'),
        ('Dakneshwori', 'Dakneshwori'),
        ('Belhi Chapena', 'Belhi Chapena'),
        ('Bishnupur', 'Bishnupur'),
        ('Rajbiraj', 'Rajbiraj'),
        ('Mahadewa', 'Mahadewa'),
        ('Tirahut', 'Tirahut'),
        ('Hanumannagar Kankalini', 'Hanumannagar Kankalini'),
        ('Tilathi Koiladi', 'Tilathi Koiladi'),
        ('Chhinnamasta', 'Chhinnamasta'),
        ('Lahan', 'Lahan'),
        ('Dhangadhimai', 'Dhangadhimai'),
        ('Golbazar', 'Golbazar'),
        ('Mirchaiya', 'Mirchaiya'),
        ('Karjanha', 'Karjanha'),
        ('Kalyanpur', 'Kalyanpur'),
        ('Naraha', 'Naraha'),
        ('Bishnupur', 'Bishnupur'),
        ('Arnama', 'Arnama'),
        ('Sukhipur', 'Sukhipur'),
        ('Laxmipur Patari', 'Laxmipur Patari'),
        ('Sakhuwa Nankarkatti', 'Sakhuwa Nankarkatti'),
        ('Bhagawanpur', 'Bhagawanpur'),
        ('Nawarajpur', 'Nawarajpur'),
        ('Bariyarpatti', 'Bariyarpatti'),
        ('Aurahi', 'Aurahi'),
        ('Siraha', 'Siraha'),
        ('DHANUSA', 'DHANUSA'),
        ('Ganeshman Charnath', 'Ganeshman Charnath'),
        ('Dhanushadham', 'Dhanushadham'),
        ('Mithila', 'Mithila'),
        ('Bateshwor', 'Bateshwor'),
        ('Chhireshwornath', 'Chhireshwornath'),
        ('Laxminiya', 'Laxminiya'),
        ('Mithila Bihari', 'Mithila Bihari'),
        ('Hansapur', 'Hansapur'),
        ('Sabaila', 'Sabaila'),
        ('Shahidnagar', 'Shahidnagar'),
        ('Kamala', 'Kamala'),
        ('Janak Nandini', 'Janak Nandini'),
        ('Bideha', 'Bideha'),
        ('Aurahi', 'Aurahi'),
        ('Janakpur', 'Janakpur'),
        ('Dhanauji', 'Dhanauji'),
        ('Nagarain', 'Nagarain'),
        ('Mukhiyapatti Musaharmiya', 'Mukhiyapatti Musaharmiya'),
        ('MAHOTTARI', 'MAHOTTARI'),
        ('Bardibas', 'Bardibas'),
        ('Gaushala', 'Gaushala'),
        ('Sonama', 'Sonama'),
        ('Aurahi', 'Aurahi'),
        ('Bhangaha', 'Bhangaha'),
        ('Loharpatti', 'Loharpatti'),
        ('Balawa', 'Balawa'),
        ('Ram Gopalpur', 'Ram Gopalpur'),
        ('Samsi', 'Samsi'),
        ('Manara Shisawa', 'Manara Shisawa'),
        ('Ekadara', 'Ekadara'),
        ('Mahottari', 'Mahottari'),
        ('Pipara', 'Pipara'),
        ('Matihani', 'Matihani'),
        ('Jaleshwor', 'Jaleshwor'),
        ('Lalbandi', 'Lalbandi'),
        ('Hariwan', 'Hariwan'),
        ('Bagmati', 'Bagmati'),
        ('Barahathawa', 'Barahathawa'),
        ('Haripur', 'Haripur'),
        ('Ishworpur', 'Ishworpur'),
        ('Haripurwa', 'Haripurwa'),
        ('Parsa', 'Parsa'),
        ('Brahmapuri', 'Brahmapuri'),
        ('Chandranagar', 'Chandranagar'),
        ('Kabilashi', 'Kabilashi'),
        ('Chakraghatta', 'Chakraghatta'),
        ('Basbariya', 'Basbariya'),
        ('Dhanakaul', 'Dhanakaul'),
        ('Ramnagar', 'Ramnagar'),
        ('Balara', 'Balara'),
        ('Godaita', 'Godaita'),
        ('Bishnu', 'Bishnu'),
        ('Kaudena', 'Kaudena'),
        ('Malangawa', 'Malangawa'),
        ('Chandrapur', 'Chandrapur'),
        ('Gujara', 'Gujara'),
        ('Phatuwa Bijayapur', 'Phatuwa Bijayapur'),
        ('Katahariya', 'Katahariya'),
        ('Brindaban', 'Brindaban'),
        ('Gadhimai', 'Gadhimai'),
        ('Madhav Narayan', 'Madhav Narayan'),
        ('Garuda', 'Garuda'),
        ('Dewahi Gonahi', 'Dewahi Gonahi'),
        ('Maulapur', 'Maulapur'),
        ('Boudhimai', 'Boudhimai'),
        ('Paroha', 'Paroha'),
        ('Rajpur', 'Rajpur'),
        ('Yamunamai', 'Yamunamai'),
        ('Durga Bhagawati', 'Durga Bhagawati'),
        ('Rajdevi', 'Rajdevi'),
        ('Gaur', 'Gaur'),
        ('Ishanath', 'Ishanath'),
        ('Nijagadh', 'Nijagadh'),
        ('Kolhabi', 'Kolhabi'),
        ('Jitpur Simara', 'Jitpur Simara'),
        ('Parawanipur', 'Parawanipur'),
        ('Prasauni', 'Prasauni'),
        ('Bishrampur', 'Bishrampur'),
        ('Pheta', 'Pheta'),
        ('Kalaiya', 'Kalaiya'),
        ('Karaiyamai', 'Karaiyamai'),
        ('Baragadhi', 'Baragadhi'),
        ('Aadarsha Kotwal', 'Aadarsha Kotwal'),
        ('Simroungadh', 'Simroungadh'),
        ('Pacharauta', 'Pacharauta'),
        ('Mahagadhimai', 'Mahagadhimai'),
        ('Devtal', 'Devtal'),
        ('Subarna', 'Subarna'),
        ('Thori', 'Thori'),
        ('Jirabhawani', 'Jirabhawani'),
        ('Jagarnathpur', 'Jagarnathpur'),
        ('Paterwa Sugauli', 'Paterwa Sugauli'),
        ('Sakhuwa Prasauni', 'Sakhuwa Prasauni'),
        ('Parsagadhi', 'Parsagadhi'),
        ('Birgunj', 'Birgunj'),
        ('Bahudarmai', 'Bahudarmai'),
        ('Pokhariya', 'Pokhariya'),
        ('Kalikamai', 'Kalikamai'),
        ('Dhobini', 'Dhobini'),
        ('Chhipaharmai', 'Chhipaharmai'),
        ('Pakaha Mainpur', 'Pakaha Mainpur'),
        ('Bindabasini', 'Bindabasini'),
        ('Gaurishankar', 'Gaurishankar'),
        ('Bigu', 'Bigu'),
        ('Kalinchowk', 'Kalinchowk'),
        ('Baitedhar', 'Baitedhar'),
        ('Jiri', 'Jiri'),
        ('Tamakoshi', 'Tamakoshi'),
        ('Melung', 'Melung'),
        ('Shailung', 'Shailung'),
        ('Bhimeshwor', 'Bhimeshwor'),
        ('Bhotekoshi', 'Bhotekoshi'),
        ('Jugal', 'Jugal'),
        ('Panchpokhari Thangpal', 'Panchpokhari Thangpal'),
        ('Helambu', 'Helambu'),
        ('Melanchi', 'Melanchi'),
        ('Indrawoti', 'Indrawoti'),
        ('Choutara Sangachowkgadhi', 'Choutara Sangachowkgadhi'),
        ('Balephi', 'Balephi'),
        ('Bahrabise', 'Bahrabise'),
        ('Tripurasundari', 'Tripurasundari'),
        ('Lisankhu Pakhar', 'Lisankhu Pakhar'),
        ('Sunkoshi', 'Sunkoshi'),
        ('Gosaikunda', 'Gosaikunda'),
        ('Parbatikunda', 'Parbatikunda'),
        ('Uttargaya', 'Uttargaya'),
        ('Kalika', 'Kalika'),
        ('Naukunda', 'Naukunda'),
        ('Rubi Valley', 'Rubi Valley'),
        ('Khaniyabas', 'Khaniyabas'),
        ('Ganga Jamuna', 'Ganga Jamuna'),
        ('Tripurasundari', 'Tripurasundari'),
        ('Netrawati', 'Netrawati'),
        ('Nilkhantha', 'Nilkhantha'),
        ('Jwalamukhi', 'Jwalamukhi'),
        ('Siddhalek', 'Siddhalek'),
        ('Benighat Rorang', 'Benighat Rorang'),
        ('Gajuri', 'Gajuri'),
        ('Galchhi', 'Galchhi'),
        ('Thakre', 'Thakre'),
        ('Dhunibenshi', 'Dhunibenshi'),
        ('Dupcheshwor', 'Dupcheshwor'),
        ('Tadi', 'Tadi'),
        ('Suryagadhi', 'Suryagadhi'),
        ('Bidur', 'Bidur'),
        ('Kispang', 'Kispang'),
        ('Meghang', 'Meghang'),
        ('Tarakeshwor', 'Tarakeshwor'),
        ('Belkotgadhi', 'Belkotgadhi'),
        ('Likhu', 'Likhu'),
        ('Panchakanya', 'Panchakanya'),
        ('Shivapuri', 'Shivapuri'),
        ('Kakani', 'Kakani'),
        ('Shankharapur', 'Shankharapur'),
        ('Kageshwori Manahara', 'Kageshwori Manahara'),
        ('Gokarneshwor', 'Gokarneshwor'),
        ('Budhanilkhantha', 'Budhanilkhantha'),
        ('Tokha', 'Tokha'),
        ('Tarakeshwor', 'Tarakeshwor'),
        ('Nagarjun', 'Nagarjun'),
        ('Kathmandu', 'Kathmandu'),
        ('Kirtipur', 'Kirtipur'),
        ('Chandragiri', 'Chandragiri'),
        ('Dakshinkali', 'Dakshinkali'),
        ('Changunarayan', 'Changunarayan'),
        ('Bhaktapur', 'Bhaktapur'),
        ('Madhyapur Thimi', 'Madhyapur Thimi'),
        ('Suryabinayak', 'Suryabinayak'),
        ('Mahalaxmi', 'Mahalaxmi'),
        ('Lalitpur', 'Lalitpur'),
        ('Godawari', 'Godawari'),
        ('Konjyosom', 'Konjyosom'),
        ('Mahankal', 'Mahankal'),
        ('Bagmati', 'Bagmati'),
        ('Chauri Deurali', 'Chauri Deurali'),
        ('Bhumlu', 'Bhumlu'),
        ('Mandan Deupur', 'Mandan Deupur'),
        ('Banepa', 'Banepa'),
        ('Dhulikhel', 'Dhulikhel'),
        ('Panchkhal', 'Panchkhal'),
        ('Temal', 'Temal'),
        ('Namobuddha', 'Namobuddha'),
        ('Panauti', 'Panauti'),
        ('Bethanchowk', 'Bethanchowk'),
        ('Roshi', 'Roshi'),
        ('Mahabharat', 'Mahabharat'),
        ('Khanikhola', 'Khanikhola'),
        ('Umakunda', 'Umakunda'),
        ('Gokulganga', 'Gokulganga'),
        ('Likhu', 'Likhu'),
        ('Ramechhap', 'Ramechhap'),
        ('Manthali', 'Manthali'),
        ('Khandadevi', 'Khandadevi'),
        ('Doramba', 'Doramba'),
        ('Sunapati', 'Sunapati'),
        ('Dudhouli', 'Dudhouli'),
        ('Phikkal', 'Phikkal'),
        ('Tinpatan', 'Tinpatan'),
        ('Golanjor', 'Golanjor'),
        ('Kamalamai', 'Kamalamai'),
        ('Sunkoshi', 'Sunkoshi'),
        ('Ghyanglekha', 'Ghyanglekha'),
        ('Marin', 'Marin'),
        ('Hariharpurgaghi', 'Hariharpurgaghi'),
        ('Indrasarowar', 'Indrasarowar'),
        ('Thaha', 'Thaha'),
        ('Kailash', 'Kailash'),
        ('Raksirang', 'Raksirang'),
        ('Manahari', 'Manahari'),
        ('Hetauda', 'Hetauda'),
        ('Bhimphedi', 'Bhimphedi'),
        ('Makawanpurgadhi', 'Makawanpurgadhi'),
        ('Bakaiya', 'Bakaiya'),
        ('Bagmati', 'Bagmati'),
        ('CHITAWAN', 'CHITAWAN'),
        ('Rapti', 'Rapti'),
        ('Kalika', 'Kalika'),
        ('Ichchha Kamana', 'Ichchha Kamana'),
        ('Bharatpur', 'Bharatpur'),
        ('Ratnanagar', 'Ratnanagar'),
        ('Khairahani', 'Khairahani'),
        ('Madi', 'Madi'),
        ('Chumanubri', 'Chumanubri'),
        ('Ajirkot', 'Ajirkot'),
        ('Sulikot', 'Sulikot'),
        ('Dharche', 'Dharche'),
        ('Aarughat', 'Aarughat'),
        ('Bhimsen', 'Bhimsen'),
        ('Siranchowk', 'Siranchowk'),
        ('Palungtar', 'Palungtar'),
        ('Gorkha', 'Gorkha'),
        ('Shahid Lakhan', 'Shahid Lakhan'),
        ('Gandaki', 'Gandaki'),
        ('Naraphu', 'Naraphu'),
        ('Neshang', 'Neshang'),
        ('Chame', 'Chame'),
        ('Nashong', 'Nashong'),
        ('Dalome', 'Dalome'),
        ('Gharpajhong', 'Gharpajhong'),
        ('Bahragaun Muktikshetra', 'Bahragaun Muktikshetra'),
        ('Lomanthang', 'Lomanthang'),
        ('Thasang', 'Thasang'),
        ('Annapurna', 'Annapurna'),
        ('Raghuganga', 'Raghuganga'),
        ('Dhawalagiri', 'Dhawalagiri'),
        ('Malika', 'Malika'),
        ('Mangala', 'Mangala'),
        ('Beni', 'Beni'),
        ('Madi', 'Madi'),
        ('Machhapuchchhre', 'Machhapuchchhre'),
        ('Annapurna', 'Annapurna'),
        ('Pokhara Lekhnath', 'Pokhara Lekhnath'),
        ('Rupa', 'Rupa'),
        ('Dordi', 'Dordi'),
        ('Marshyangdi', 'Marshyangdi'),
        ('Kwhola Sothar', 'Kwhola Sothar'),
        ('Madhya Nepal', 'Madhya Nepal'),
        ('Bensi Shahar', 'Bensi Shahar'),
        ('Sundarbazar', 'Sundarbazar'),
        ('Rainas', 'Rainas'),
        ('Dudhapokhari', 'Dudhapokhari'),
        ('Bhanu', 'Bhanu'),
        ('Byas', 'Byas'),
        ('Myagde', 'Myagde'),
        ('Shuklagandaki', 'Shuklagandaki'),
        ('Bhimad', 'Bhimad'),
        ('Ghiring', 'Ghiring'),
        ('Rhishing', 'Rhishing'),
        ('Devghat', 'Devghat'),
        ('Bandipur', 'Bandipur'),
        ('Aanbu Khaireni', 'Aanbu Khaireni'),
        ('Gaidakot', 'Gaidakot'),
        ('Bulingtar', 'Bulingtar'),
        ('Bungdikali', 'Bungdikali'),
        ('Hupsekot', 'Hupsekot'),
        ('Devchuli', 'Devchuli'),
        ('Kawasoti', 'Kawasoti'),
        ('Madhya Bindu', 'Madhya Bindu'),
        ('Binayi Tribeni', 'Binayi Tribeni'),
        ('Putalibazar', 'Putalibazar'),
        ('Phedikhola', 'Phedikhola'),
        ('Aandhikhola', 'Aandhikhola'),
        ('Arjun Choupari', 'Arjun Choupari'),
        ('Bhirkot', 'Bhirkot'),
        ('Biruwa', 'Biruwa'),
        ('Harinas', 'Harinas'),
        ('Chapakot', 'Chapakot'),
        ('Walling', 'Walling'),
        ('Galyang', 'Galyang'),
        ('Kaligandaki', 'Kaligandaki'),
        ('Modi', 'Modi'),
        ('Jaljala', 'Jaljala'),
        ('Kushma', 'Kushma'),
        ('Phalebas', 'Phalebas'),
        ('Mahashila', 'Mahashila'),
        ('Bihadi', 'Bihadi'),
        ('Paiyu', 'Paiyu'),
        ('Baglung', 'Baglung'),
        ('Kathekhola', 'Kathekhola'),
        ('Tarakhola', 'Tarakhola'),
        ('Tamankhola', 'Tamankhola'),
        ('Dhorpatan', 'Dhorpatan'),
        ('Nisikhola', 'Nisikhola'),
        ('Badigad', 'Badigad'),
        ('Galkot', 'Galkot'),
        ('Bareng', 'Bareng'),
        ('Jaimuni', 'Jaimuni'),
        ('Putha Uttanganga', 'Putha Uttanganga'),
        ('Sisne', 'Sisne'),
        ('Bhoome', 'Bhoome'),
        ('Sunchhahari', 'Sunchhahari'),
        ('Thawang', 'Thawang'),
        ('Paribartan', 'Paribartan'),
        ('Gangadev', 'Gangadev'),
        ('Madi', 'Madi'),
        ('Tribeni', 'Tribeni'),
        ('Rolpa', 'Rolpa'),
        ('Runtigadhi', 'Runtigadhi'),
        ('Sunil Smriti', 'Sunil Smriti'),
        ('Lungri', 'Lungri'),
        ('Gaumukhi', 'Gaumukhi'),
        ('Naubahini', 'Naubahini'),
        ('Jhimaruk', 'Jhimaruk'),
        ('Pyuthan', 'Pyuthan'),
        ('Sworgadwari', 'Sworgadwari'),
        ('Mandavi', 'Mandavi'),
        ('Mallarani', 'Mallarani'),
        ('Aairawati', 'Aairawati'),
        ('Sarumarani', 'Sarumarani'),
        ('Kali Gandaki', 'Kali Gandaki'),
        ('Satyawoti', 'Satyawoti'),
        ('Chandrakot', 'Chandrakot'),
        ('Musikot', 'Musikot'),
        ('Isma', 'Isma'),
        ('Malika', 'Malika'),
        ('Madane', 'Madane'),
        ('Dhurkot', 'Dhurkot'),
        ('Resunga', 'Resunga'),
        ('Gulmi Durbar', 'Gulmi Durbar'),
        ('Chhatrakot', 'Chhatrakot'),
        ('Ruru', 'Ruru'),
        ('Chhatradev', 'Chhatradev'),
        ('Malarani', 'Malarani'),
        ('Bhumikasthan', 'Bhumikasthan'),
        ('Sandhikharka', 'Sandhikharka'),
        ('Panini', 'Panini'),
        ('Shitaganga', 'Shitaganga'),
        ('Rampur', 'Rampur'),
        ('Purbakhola', 'Purbakhola'),
        ('Rambha', 'Rambha'),
        ('Baganaskali', 'Baganaskali'),
        ('Tansen', 'Tansen'),
        ('Ribdikot', 'Ribdikot'),
        ('Rainadevi Chhahara', 'Rainadevi Chhahara'),
        ('Tinau', 'Tinau'),
        ('Mathagadhi', 'Mathagadhi'),
        ('Nisdi', 'Nisdi'),
        ('Bardaghat', 'Bardaghat'),
        ('Sunawal', 'Sunawal'),
        ('Ramgram', 'Ramgram'),
        ('Palhinandan', 'Palhinandan'),
        ('Sarawal', 'Sarawal'),
        ('Pratapapur', 'Pratapapur'),
        ('Susta', 'Susta'),
        ('Devdaha', 'Devdaha'),
        ('Butwal', 'Butwal'),
        ('Sainamaina', 'Sainamaina'),
        ('Kanchan', 'Kanchan'),
        ('Gaidahawa', 'Gaidahawa'),
        ('Suddhodhan', 'Suddhodhan'),
        ('Siyari', 'Siyari'),
        ('Tilottama', 'Tilottama'),
        ('Om Satiya', 'Om Satiya'),
        ('Rohini', 'Rohini'),
        ('Siddharthanagar', 'Siddharthanagar'),
        ('Mayadevi', 'Mayadevi'),
        ('Lumbini Sanskritik', 'Lumbini Sanskritik'),
        ('Kotahimai', 'Kotahimai'),
        ('Sammarimai', 'Sammarimai'),
        ('Marchawari', 'Marchawari'),
        ('Banganga', 'Banganga'),
        ('Buddhabhumi', 'Buddhabhumi'),
        ('Shivaraj', 'Shivaraj'),
        ('Bijayanagar', 'Bijayanagar'),
        ('Krishnanagar', 'Krishnanagar'),
        ('Maharajganj', 'Maharajganj'),
        ('Kapilbastu', 'Kapilbastu'),
        ('Yasodhara', 'Yasodhara'),
        ('Mayadevi', 'Mayadevi'),
        ('Shuddhodhan', 'Shuddhodhan'),
        ('Bangalachuli', 'Bangalachuli'),
        ('Ghorahi', 'Ghorahi'),
        ('Tulsipur', 'Tulsipur'),
        ('Shantinagar', 'Shantinagar'),
        ('Babai', 'Babai'),
        ('Dangisharan', 'Dangisharan'),
        ('Lamahi', 'Lamahi'),
        ('Rapti', 'Rapti'),
        ('Gadhawa', 'Gadhawa'),
        ('Rajpur', 'Rajpur'),
        ('Rapti Sonari', 'Rapti Sonari'),
        ('Kohalpur', 'Kohalpur'),
        ('Baijanath', 'Baijanath'),
        ('Khajura', 'Khajura'),
        ('Janaki', 'Janaki'),
        ('Nepalganj', 'Nepalganj'),
        ('Duduwa', 'Duduwa'),
        ('Narainapur', 'Narainapur'),
        ('Bansgadhi', 'Bansgadhi'),
        ('Barbardiya', 'Barbardiya'),
        ('Thakurbaba', 'Thakurbaba'),
        ('Geruwa', 'Geruwa'),
        ('Rajapur', 'Rajapur'),
        ('Madhuwan', 'Madhuwan'),
        ('Gulariya', 'Gulariya'),
        ('Badhaiyatal', 'Badhaiyatal'),
        ('Dolpo Buddha', 'Dolpo Buddha'),
        ('Shey Phoksundo', 'Shey Phoksundo'),
        ('Jagadulla', 'Jagadulla'),
        ('Mudkechula', 'Mudkechula'),
        ('Tripurasundari', 'Tripurasundari'),
        ('Thulibheri', 'Thulibheri'),
        ('Kaike', 'Kaike'),
        ('Chharka Tangsong', 'Chharka Tangsong'),
        ('Mugumkarmarog', 'Mugumkarmarog'),
        ('Chhayanath Rara', 'Chhayanath Rara'),
        ('Soru', 'Soru'),
        ('Khatyad', 'Khatyad'),
        ('Chankheli', 'Chankheli'),
        ('Kharpunath', 'Kharpunath'),
        ('Simkot', 'Simkot'),
        ('Namkha', 'Namkha'),
        ('Sarkegad', 'Sarkegad'),
        ('Adanchuli', 'Adanchuli'),
        ('Tanjakot', 'Tanjakot'),
        ('Patarasi', 'Patarasi'),
        ('Kanaka Sundari', 'Kanaka Sundari'),
        ('Sinja', 'Sinja'),
        ('Chandannath', 'Chandannath'),
        ('Guthichaur', 'Guthichaur'),
        ('Tatopani', 'Tatopani'),
        ('Tila', 'Tila'),
        ('Hima', 'Hima'),
        ('Palata', 'Palata'),
        ('Pachal Jharana', 'Pachal Jharana'),
        ('Raskot', 'Raskot'),
        ('Sanni Tribeni', 'Sanni Tribeni'),
        ('Naraharinath', 'Naraharinath'),
        ('Khandachakra', 'Khandachakra'),
        ('Tilagupha', 'Tilagupha'),
        ('Mahawai', 'Mahawai'),
        ('Kalika', 'Kalika'),
        ('Naumule', 'Naumule'),
        ('Mahabu', 'Mahabu'),
        ('Bhairabi', 'Bhairabi'),
        ('Thantikandh', 'Thantikandh'),
        ('Aathbis', 'Aathbis'),
        ('Chamunda Bindrasaini', 'Chamunda Bindrasaini'),
        ('Dullu', 'Dullu'),
        ('Narayan', 'Narayan'),
        ('Bhagawatimai', 'Bhagawatimai'),
        ('Dungeshwor', 'Dungeshwor'),
        ('Gurans', 'Gurans'),
        ('Barekot', 'Barekot'),
        ('Kuse', 'Kuse'),
        ('Junichande', 'Junichande'),
        ('Chhedagad', 'Chhedagad'),
        ('Shivalaya', 'Shivalaya'),
        ('Bheri Malika', 'Bheri Malika'),
        ('Tribeni Nalagad', 'Tribeni Nalagad'),
        ('Aathabisakot', 'Aathabisakot'),
        ('Sanibheri', 'Sanibheri'),
        ('Banphikot', 'Banphikot'),
        ('Musikot', 'Musikot'),
        ('Tribeni', 'Tribeni'),
        ('Chaurjahari', 'Chaurjahari'),
        ('Darma', 'Darma'),
        ('Kumakh Malika', 'Kumakh Malika'),
        ('Banagad Kupinde', 'Banagad Kupinde'),
        ('Dhorchaur', 'Dhorchaur'),
        ('Bagachour', 'Bagachour'),
        ('Chhatreshwori', 'Chhatreshwori'),
        ('Sharada', 'Sharada'),
        ('Kalimati', 'Kalimati'),
        ('Tribeni', 'Tribeni'),
        ('Kapurkot', 'Kapurkot'),
        ('Simta', 'Simta'),
        ('Chingad', 'Chingad'),
        ('Lekabeshi', 'Lekabeshi'),
        ('Gurbhakot', 'Gurbhakot'),
        ('Bheriganga', 'Bheriganga'),
        ('Birendranagar', 'Birendranagar'),
        ('Barahatal', 'Barahatal'),
        ('Panchapuri', 'Panchapuri'),
        ('Chaukune', 'Chaukune'),
        ('Himali', 'Himali'),
        ('Gaumul', 'Gaumul'),
        ('Budhinanda', 'Budhinanda'),
        ('Swami Kartik', 'Swami Kartik'),
        ('Jagannath', 'Jagannath'),
        ('Badimalika', 'Badimalika'),
        ('Khaptad Chhededaha', 'Khaptad Chhededaha'),
        ('Budhiganga', 'Budhiganga'),
        ('Tribeni', 'Tribeni'),
        ('Kanda', 'Kanda'),
        ('Bungal', 'Bungal'),
        ('Surma', 'Surma'),
        ('Talkot', 'Talkot'),
        ('Masta', 'Masta'),
        ('Jayaprithbi', 'Jayaprithbi'),
        ('Chhabis Pathibhara', 'Chhabis Pathibhara'),
        ('Durgathali', 'Durgathali'),
        ('Kedarsyun', 'Kedarsyun'),
        ('Bitthadchir', 'Bitthadchir'),
        ('Thalara', 'Thalara'),
        ('Khaptad Chhanna', 'Khaptad Chhanna'),
        ('Byas', 'Byas'),
        ('Duhun', 'Duhun'),
        ('Mahakali', 'Mahakali'),
        ('Naugad', 'Naugad'),
        ('Apihimal', 'Apihimal'),
        ('Marma', 'Marma'),
        ('Shailyashikhar', 'Shailyashikhar'),
        ('Malikarjun', 'Malikarjun'),
        ('Lekam', 'Lekam'),
        ('Dilasaini', 'Dilasaini'),
        ('Dogada Kedar', 'Dogada Kedar'),
        ('Puchaundi', 'Puchaundi'),
        ('Surnaya', 'Surnaya'),
        ('Dasharathchand', 'Dasharathchand'),
        ('Pancheshwor', 'Pancheshwor'),
        ('Shivanath', 'Shivanath'),
        ('Melauli', 'Melauli'),
        ('Patan', 'Patan'),
        ('Sigas', 'Sigas'),
        ('Nawadurga', 'Nawadurga'),
        ('Amargadhi', 'Amargadhi'),
        ('Ajayameru', 'Ajayameru'),
        ('Bhageshwor', 'Bhageshwor'),
        ('Parashuram', 'Parashuram'),
        ('Aalital', 'Aalital'),
        ('Ganyapdhura', 'Ganyapdhura'),
        ('Purbichouki', 'Purbichouki'),
        ('Sayal', 'Sayal'),
        ('Aadarsha', 'Aadarsha'),
        ('Shikhar', 'Shikhar'),
        ('Dipayal Silgadhi', 'Dipayal Silgadhi'),
        ('K.I. Singh', 'K.I. Singh'),
        ('Bogatan', 'Bogatan'),
        ('Badi Kedar', 'Badi Kedar'),
        ('Jorayal', 'Jorayal'),
        ('Panchdebal Binayak', 'Panchdebal Binayak'),
        ('Ramaroshan', 'Ramaroshan'),
        ('Mellekh', 'Mellekh'),
        ('Sanphebagar', 'Sanphebagar'),
        ('Chaurpati', 'Chaurpati'),
        ('Mangalsen', 'Mangalsen'),
        ('Bannigadhi Jayagadh', 'Bannigadhi Jayagadh'),
        ('Kamal Bazar', 'Kamal Bazar'),
        ('Dhakari', 'Dhakari'),
        ('Turmakhand', 'Turmakhand'),
        ('Mohanyal', 'Mohanyal'),
        ('Chure', 'Chure'),
        ('Godawari', 'Godawari'),
        ('Gauriganga', 'Gauriganga'),
        ('Ghodaghodi', 'Ghodaghodi'),
        ('Bardagoriya', 'Bardagoriya'),
        ('Lamki Chuha', 'Lamki Chuha'),
        ('Janaki', 'Janaki'),
        ('Joshipur', 'Joshipur'),
        ('Tikapur', 'Tikapur'),
        ('Bhajani', 'Bhajani'),
        ('Kailari', 'Kailari'),
        ('Dhangadhi', 'Dhangadhi'),
        ('Krishnapur', 'Krishnapur'),
        ('Shuklaphanta', 'Shuklaphanta'),
        ('Bedkot', 'Bedkot'),
        ('Bhimdatta', 'Bhimdatta'),
        ('Mahakali', 'Mahakali'),
        ('Laljhadi', 'Laljhadi'),
        ('Punarbas', 'Punarbas'),
        ('Belouri', 'Belouri'),
        ('Beldandi', 'Beldandi'),
    )
    DISTRICTS = (
        ('Sunsari', 'Sunsari'),
        ('Syangja', 'Syangja'),
        ('Kalikot', 'Kalikot'),
        ('Dadeldhura', 'Dadeldhura'),
        ('Morang', 'Morang'),
        ('Tanahu', 'Tanahu'),
        ('Banke', 'Banke'),
        ('Salyan', 'Salyan'),
        ('Humla', 'Humla'),
        ('Kanchanpur', 'Kanchanpur'),
        ('Bajhang', 'Bajhang'),
        ('Myagdi', 'Myagdi'),
        ('Mustang', 'Mustang'),
        ('Rautahat', 'Rautahat'),
        ('Bajura', 'Bajura'),
        ('Sindhupalchok', 'Sindhupalchok'),
        ('Arghakhanchi', 'Arghakhanchi'),
        ('Kapilbastu', 'Kapilbastu'),
        ('Pyuthan', 'Pyuthan'),
        ('Dailekh', 'Dailekh'),
        ('Nawalparasi West', 'Nawalparasi West'),
        ('Dhading', 'Dhading'),
        ('Rukum West', 'Rukum West'),
        ('Solukhumbu', 'Solukhumbu'),
        ('Okhaldhunga', 'Okhaldhunga'),
        ('Khotang', 'Khotang'),
        ('Jhapa', 'Jhapa'),
        ('Ilam', 'Ilam'),
        ('Jumla', 'Jumla'),
        ('Palpa', 'Palpa'),
        ('Sankhuwasabha', 'Sankhuwasabha'),
        ('Siraha', 'Siraha'),
        ('Gulmi', 'Gulmi'),
        ('Mohattari', 'Mohattari'),
        ('Udayapur', 'Udayapur'),
        ('Chitwan', 'Chitwan'),
        ('Darchula', 'Darchula'),
        ('Bara', 'Bara'),
        ('Sarlahi', 'Sarlahi'),
        ('Dang', 'Dang'),
        ('Dolakha', 'Dolakha'),
        ('Rolpa', 'Rolpa'),
        ('Gorkha', 'Gorkha'),
        ('Rupandehi', 'Rupandehi'),
        ('Doti', 'Doti'),
        ('Ramechhap', 'Ramechhap'),
        ('Manang', 'Manang'),
        ('Nuwakot', 'Nuwakot'),
        ('Surkhet', 'Surkhet'),
        ('Parsa', 'Parsa'),
        ('Rasuwa', 'Rasuwa'),
        ('Nawalparasi East', 'Nawalparasi East'),
        ('Kathmandu', 'Kathmandu'),
        ('Saptari', 'Saptari'),
        ('Lalitpur', 'Lalitpur'),
        ('Dhankuta', 'Dhankuta'),
        ('Panchthar', 'Panchthar'),
        ('Terhathum', 'Terhathum'),
        ('Bhojpur', 'Bhojpur'),
        ('Parbat', 'Parbat'),
        ('Baglung', 'Baglung'),
        ('Sindhuli', 'Sindhuli'),
        ('Baitadi', 'Baitadi'),
        ('Lamjung', 'Lamjung'),
        ('Kailali', 'Kailali'),
        ('Kaski', 'Kaski'),
        ('Jajarkot', 'Jajarkot'),
        ('Kavrepalanchok', 'Kavrepalanchok'),
        ('Taplejung', 'Taplejung'),
        ('Rukum East', 'Rukum East'),
        ('Dhunasa', 'Dhunasa'),
        ('Dolpa', 'Dolpa'),
        ('Makwanpur', 'Makwanpur'),
        ('Province', 'Province'),
        ('Bardiya', 'Bardiya'),
        ('Bhaktapur', 'Bhaktapur'),
        ('Achham', 'Achham'),
        ('Mugu', 'Mugu')
    )
    PROVINCES = (
        ("Province 1", "Province 1"),
        ("Province 2", "Province 2"),
        ("Bagmati Province", "Bagmati Province"),
        ("Gandaki Province", "Gandaki Province"),
        ("Lumbini Province", "Lumbini Province"),
        ("Karnali Province", "Karnali Province"),
        ("Sudurpaschim Province", "Sudurpaschim Province")
    )
    IDENTITIES = (
        ("Citizenship", "Citizenship"),
        ("Passport", "Passport"),
        ("Driving License", "Driving License")
    )
    DISABILITIES = (
        ("Hearing", "Hearing"),
        ("Seeing", "Seeing"),
        ("Movement", "Movement"),
        ("Others", "Others"),
        ("None", "None")
    )
    CALENDAR = (
        ('BS', 'BS'),
        ('AD', 'AD')
    )

    # general_information
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255)

    # identity
    photo = models.ImageField(null=True, blank=True, upload_to='images/trainer/',
                              default='images/trainer/default_trainer.png')
    phone_number = models.CharField(max_length=255, validators=[phone_regex],
                                    help_text="Phone number must be entered in the format: '000-555555' or '9999999999'.")
    email = models.EmailField()

    # demographics
    gender = models.CharField(max_length=255, choices=GENDERS)
    marital_status = models.CharField(max_length=255, choices=MARITAL_STATUS)
    migration_status = models.CharField(max_length=255, choices=MIGRATION_STATUS)
    special_focus_group = models.CharField(max_length=255, choices=SPECIAL_FOCUS_GROUP)
    religion = models.CharField(max_length=255, choices=RELIGIONS)
    ethnicity = models.CharField(max_length=255, choices=ETHNICITIES)
    disability = models.CharField(max_length=255, choices=DISABILITIES)

    # address
    permanent_province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name="trainer_permanent_province")
    permanent_district = models.ForeignKey(District, on_delete=models.CASCADE, related_name="trainer_permanent_district")
    permanent_municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, related_name="trainer_permanent_municipality")
    permanent_ward_number = models.PositiveIntegerField(choices=WARD_NUMBER)
    permanent_street_name = models.CharField(max_length=255, null=True, blank=True)
    permanent_tole_name = models.CharField(max_length=255, null=True, blank=True)
    permanent_house_number = models.PositiveIntegerField(null=True, blank=True)
    permanent_phone_number = models.CharField(max_length=255, validators=[phone_regex],
                                              help_text="Phone number must be entered in the format: '000-555555' or '9999999999'.")

    temporary_province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name="trainer_temporary_province")
    temporary_district = models.ForeignKey(District, on_delete=models.CASCADE, related_name="trainer_temporary_district")
    temporary_municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, related_name="trainer_temporary_municipality")
    temporary_ward_number = models.PositiveIntegerField(choices=WARD_NUMBER)
    temporary_street_name = models.CharField(max_length=255, null=True, blank=True)
    temporary_tole_name = models.CharField(max_length=255, null=True, blank=True)
    temporary_house_number = models.PositiveIntegerField(null=True, blank=True)
    temporary_phone_number = models.CharField(max_length=255, validators=[phone_regex],
                                              help_text="Phone number must be entered in the format: '000-555555' or '9999999999'.")

    calendar = models.CharField(max_length=255, choices=CALENDAR)

    date_of_birth_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    date_of_joining_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    date_of_birth_AD = models.DateField(null=True, blank=True)
    date_of_joining_AD = models.DateField(null=True, blank=True)

    # family
    father_first_name = models.CharField(max_length=255)
    father_middle_name = models.CharField(max_length=255, null=True, blank=True)
    father_last_name = models.CharField(max_length=255)
    father_occupation = models.CharField(max_length=255)
    mother_first_name = models.CharField(max_length=255)
    mother_middle_name = models.CharField(max_length=255, null=True, blank=True)
    mother_last_name = models.CharField(max_length=255)
    mother_occupation = models.CharField(max_length=255)
    grandfather_first_name = models.CharField(max_length=255, null=True, blank=True)
    grandfather_middle_name = models.CharField(max_length=255, null=True, blank=True)
    grandfather_last_name = models.CharField(max_length=255, null=True, blank=True)
    spouse_first_name = models.CharField(max_length=255, null=True, blank=True)
    spouse_middle_name = models.CharField(max_length=255, null=True, blank=True)
    spouse_last_name = models.CharField(max_length=255, null=True, blank=True)

    # citizenship records
    citizenship_number = models.CharField(max_length=255)
    citizenship_issued_district = models.ForeignKey(District, on_delete=models.CASCADE, related_name="trainer_citizenship_issued_district")
    citizenship_issued_date_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    citizenship_issued_date_AD = models.DateField(null=True, blank=True)

    # pdf records
    proof_of_identity = models.CharField(max_length=255, choices=IDENTITIES)
    front = models.FileField(upload_to="files/identity/front/")
    back = models.FileField(upload_to="files/identity/back/")

    # others
    post = models.CharField(max_length=255, null=True, blank=True)
    courses = models.ManyToManyField(Course, help_text="Press Ctrl to select many")
    dss = models.ForeignKey(DSS, on_delete=models.CASCADE)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name)


class Qualification(models.Model):

    CALENDAR = (
        ('BS', 'BS'),
        ('AD', 'AD')
    )

    level = models.CharField(max_length=255)
    field = models.CharField(max_length=255)
    institute = models.CharField(max_length=255)

    calendar = models.CharField(max_length=255, choices=CALENDAR)

    started_from_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    ended_on_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    started_from_AD = models.DateField(null=True, blank=True)
    ended_on_AD = models.DateField(null=True, blank=True)

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    certificate = models.FileField(null=True, blank=True, upload_to='files/trainer/qualification')

    def __str__(self):
        return str(self.level) + " on " + str(self.field) + " from " + str(self.institute)


class Experience(models.Model):

    CALENDAR = (
        ('BS', 'BS'),
        ('AD', 'AD')
    )

    post = models.CharField(max_length=255)
    organization = models.CharField(max_length=255)

    calendar = models.CharField(max_length=255, choices=CALENDAR)

    started_from_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    ended_on_BS = NepaliDateField(null=True, blank=True, help_text="Write in YYYY-MM-DD format")
    started_from_AD = models.DateField(null=True, blank=True)
    ended_on_AD = models.DateField(null=True, blank=True)

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    certificate = models.FileField(null=True, blank=True, upload_to='files/trainer/experience')

    def __str__(self):
        return str(self.post) + " at " + str(self.organization)
