# Generated by Django 3.2.4 on 2021-06-10 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('location', '0001_initial'),
        ('trainee', '0001_initial'),
        ('trainer', '0001_initial'),
        ('dss', '0001_initial'),
        ('course_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.trainee'),
        ),
        migrations.AddField(
            model_name='employment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_class.courseclass'),
        ),
        migrations.AddField(
            model_name='employment',
            name='dss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dss'),
        ),
        migrations.AddField(
            model_name='employment',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stakeholder.stakeholder'),
        ),
        migrations.AddField(
            model_name='employment',
            name='office_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AddField(
            model_name='employment',
            name='office_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.municipality'),
        ),
        migrations.AddField(
            model_name='employment',
            name='office_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province'),
        ),
        migrations.AddField(
            model_name='employment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.trainee'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='dss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dss'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='trainers',
            field=models.ManyToManyField(help_text='Use Ctrl to select multiple trainers', to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
