# Generated by Django 3.2.4 on 2021-08-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='days_per_week',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=6, null=True),
        ),
    ]
