# Generated by Django 3.2.4 on 2021-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0003_alter_courseclass_days_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='symbol_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
