# Generated by Django 3.2.4 on 2021-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0004_test_symbol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='assistant_trainer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='coordinator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='venue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
