# Generated by Django 3.2.4 on 2021-06-10 04:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nepali_datetime_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('calendar', models.CharField(choices=[('BS', 'BS'), ('AD', 'AD')], max_length=255)),
                ('estimated_date_of_purchase_BS', nepali_datetime_field.models.NepaliDateField(blank=True, help_text='Write in YYYY-MM-DD format', null=True)),
                ('estimated_date_of_purchase_AD', models.DateField(blank=True, null=True)),
                ('requirement_type', models.CharField(choices=[('Land', 'Land'), ('Building', 'Building'), ('Furniture', 'Furniture'), ('Automobile', 'Automobile'), ('Electronic', 'Electronic'), ('Others', 'Others')], max_length=255)),
                ('unit', models.CharField(blank=True, choices=[('Pieces', 'Pieces'), ('Unit', 'Unit'), ('Boxes', 'Boxes'), ('Cartoon', 'Cartoon'), ('Meter', 'Meter'), ('Cubic Meter', 'Cubic Meter'), ('sq.m', 'sq.m'), ('sq.KM', 'sq.KM'), ('Acres', 'Acres'), ('Hectares', 'Hectares'), ('Paisa', 'Paisa'), ('Aana', 'Aana'), ('Ropani', 'Ropani'), ('Dhur', 'Dhur'), ('Kattha', 'Kattha'), ('Bigha', 'Bigha')], max_length=255, null=True)),
                ('estimated_quantity', models.PositiveIntegerField(default=0)),
                ('estimated_price', models.PositiveIntegerField(default=0, help_text='In Rupees')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dss.dss')),
            ],
        ),
    ]
