# Generated by Django 3.2.4 on 2021-08-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210812_0844'),
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.activity'),
        ),
    ]
