# Generated by Django 3.2.4 on 2021-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
