# Generated by Django 3.2.4 on 2021-08-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_name_training_training_module_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Capacity Building'},
        ),
        migrations.RenameField(
            model_name='training',
            old_name='providing_agencies',
            new_name='proposed_training_providing_agencies',
        ),
    ]
